package crypto

import (
	"context"
	"crypto/tls"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	bao "github.com/openbao/openbao/api/v2"
)

// OpenBao / HashiCorp Vault Transit adapter.
//
// This adapter wraps per-object DEKs using the Transit secrets engine. The DEK
// is generated by the gateway's engine and handed to WrapKey; the adapter only
// asks Transit to encrypt it (transit/encrypt/<key>) and later decrypt it
// (transit/decrypt/<key>). The KEK never leaves OpenBao and is non-exportable.
//
// Why Transit encrypt/decrypt rather than transit/datakey: the gateway already
// generates its own random DEK (see engine.go), so it only needs a wrap/unwrap
// service. transit/datakey would make OpenBao the DEK generator and break the
// input-plaintext -> output-envelope contract shared by every other adapter.
//
// Differences vs. the Cosmian KMIP adapter that a reader should know:
//   - There is NO client-side candidate loop / dual_read_window. The Transit
//     ciphertext is self-describing ("vault:vN:<base64>") and the server
//     auto-routes a decrypt to the embedded version N. UnwrapKey is a single
//     call; old envelopes keep decrypting until an operator raises
//     min_decryption_version server-side (a retire floor, not a client window).
//   - KeyID is synthesised ("vault-transit:<mount>/<key>") rather than returned
//     by the server. engine.go rejects a streaming decrypt when the persisted
//     KMS key ID is empty, so WrapKey MUST set a stable non-empty KeyID.
//   - The active version is owned by the server (latest_version) and read live,
//     not held in an in-memory slice.
//   - Transit issues no dynamic leases; the only lifecycle object is the auth
//     token. It is kept alive on two independent paths, because either one alone
//     leaves a hole:
//     PROACTIVE — a background goroutine drives a LifetimeWatcher and re-logs-in
//     when renewal can no longer extend the lease (see the auth & token
//     renewal section below).
//     REACTIVE  — any request rejected with 401/403 triggers an immediate
//     re-login and one retry (withAuthRetry).
//     The reactive path is not belt-and-braces: the watcher only discovers a
//     dead token when it next attempts a renewal, which is up to ~2/3 of the
//     lease away, so a token that dies out-of-band (revoked, max_ttl, or a
//     lease lost while OpenBao was unreachable) would otherwise 403 every
//     request until the lease clock caught up.

const (
	defaultOpenBaoProvider    = "openbao-transit"
	defaultOpenBaoTransitPath = "transit"
	defaultOpenBaoTimeout     = 5 * time.Second
	defaultOpenBaoSAJWTPath   = "/var/run/secrets/kubernetes.io/serviceaccount/token" //nolint:gosec // well-known path, not a credential

	// openBaoCiphertextPrefix is the fixed prefix of every Transit ciphertext.
	// The "vault:" literal is retained by OpenBao for wire compatibility.
	openBaoCiphertextPrefix = "vault:v"

	// Supported auth methods.
	openBaoAuthToken      = "token"
	openBaoAuthAppRole    = "approle"
	openBaoAuthKubernetes = "kubernetes"

	// minLoginInterval floors the interval between login ATTEMPTS on every path.
	// Without it two pathologies mint tokens as fast as the network allows:
	// re-login succeeding while requests still 403 (a role that lost its transit
	// policy), and a token that can log in but not renew-self (the policy in
	// docs/KMS_COMPATIBILITY.md with token_no_default_policy and no renew-self
	// grant). Both are unbounded token-minting loops, and a token is server
	// state — the lease table grows until storage does.
	//
	// One second, not longer: this also bounds worst-case recovery latency on
	// the reactive path, and a floor is only meant to make a storm harmless, not
	// to slow down the common case. The renewal goroutine layers exponential
	// backoff on top for the specific case of a lease it can never renew.
	minLoginInterval = time.Second
)

// OpenBaoAuthConfig selects the OpenBao authentication method and its parameters.
//
// Secret material (Token, SecretID, JWT) is expected to be already resolved by
// the caller (the config layer resolves env:/file: references). It is never
// logged or placed into a KeyEnvelope.
type OpenBaoAuthConfig struct {
	// Method is one of "token", "approle", "kubernetes". Default: "token".
	Method string
	// Mount is the auth backend mount path. Defaults per method
	// (approle -> "approle", kubernetes -> "kubernetes").
	Mount string

	// Token is the OpenBao token for the "token" method.
	Token string

	// RoleID / SecretID are the AppRole credentials.
	RoleID   string
	SecretID string

	// Role is the role name for the kubernetes method.
	Role string
	// JWTPath is the file holding the projected ServiceAccount JWT.
	// Default: defaultOpenBaoSAJWTPath.
	JWTPath string
	// JWT, when non-empty, is used verbatim instead of reading JWTPath
	// (primarily for tests).
	JWT string
}

// OpenBaoTransitOptions configures the OpenBao Transit KeyManager.
type OpenBaoTransitOptions struct {
	// Address is the OpenBao server address, e.g. "https://bao.internal:8200".
	Address string
	// TransitPath is the mount path of the Transit engine. Default: "transit".
	TransitPath string
	// KeyName is the Transit key used for DEK wrap/unwrap. Required.
	KeyName string
	// Namespace is an optional namespace prefix (OpenBao/Vault Enterprise).
	Namespace string
	// Provider overrides the Provider() string. Default: "openbao-transit".
	Provider string
	// Timeout is the per-request timeout. Default: 5s.
	Timeout time.Duration
	// TLSConfig, when set, replaces the client transport's TLS configuration.
	TLSConfig *tls.Config
	// Auth holds the authentication configuration.
	Auth OpenBaoAuthConfig

	// DisableRenewal disables the background token-renewal goroutine. Intended
	// for tests and for the "token" auth method where the operator owns the
	// token lifecycle.
	DisableRenewal bool
}

type openBaoTransitManager struct {
	mu          sync.RWMutex
	client      *bao.Client
	transitPath string
	keyName     string
	keyID       string // synthesised, stable: "vault-transit:<mount>/<key>"
	provider    string
	timeout     time.Duration
	auth        OpenBaoAuthConfig
	closed      bool

	// renewal goroutine lifecycle. stopRenew is closed by Close to signal exit;
	// renewDone is closed by the goroutine on exit.
	renewing  bool
	stopRenew chan struct{}
	renewDone chan struct{}

	// authGen increments on every successful login. A caller reads it before a
	// request and passes it back when asking for a refresh, so N concurrent 403s
	// collapse into ONE re-login: the first caller wins, the rest observe a
	// changed generation and simply retry with the new token.
	//
	// Atomic, NOT guarded by authSem. Every request reads it, and authSem is held
	// across a login round-trip — reading under that lock would park the whole
	// data plane behind the login it is waiting for.
	authGen atomic.Uint64

	// authSem serialises logins: depth-1, so send == acquire and receive ==
	// release. A channel rather than a Mutex because acquiring must be
	// cancellable — see acquireAuth.
	authSem chan struct{}
	// lastLoginAttempt floors the rate of login ATTEMPTS, not successes. Keying
	// on successes leaves the throttle disengaged exactly when login is failing
	// (a revoked secret_id, a detached policy), which is when a storm is most
	// likely and least useful. Written only under authSem.
	lastLoginAttempt time.Time
	// freshSecret hands a login performed on the data path to the renewal
	// goroutine so it re-watches the new lease instead of the stale one.
	// Buffered, depth 1, so publishing never blocks.
	freshSecret chan leaseUpdate
}

// leaseUpdate carries a lease plus the auth generation it belongs to. The
// generation is what makes the hand-off safe: the renewal goroutine may log in
// on its own while an update sits in the buffer, and a queued lease for a
// superseded token must be discarded rather than watched.
type leaseUpdate struct {
	gen    uint64
	secret *bao.Secret
}

// Compile-time assertions.
var (
	_ KeyManager          = (*openBaoTransitManager)(nil)
	_ RotatableKeyManager = (*openBaoTransitManager)(nil)
)

// NewOpenBaoTransitManager constructs an authenticated OpenBao Transit
// KeyManager. It fails closed: if the initial login fails the manager is not
// returned, so the gateway never silently downgrades to password-derived DEKs.
func NewOpenBaoTransitManager(opts OpenBaoTransitOptions) (KeyManager, error) {
	opts.Address = strings.TrimSpace(opts.Address)
	if opts.Address == "" {
		return nil, errors.New("keymanager/openbao: address is required")
	}
	opts.KeyName = strings.TrimSpace(opts.KeyName)
	if opts.KeyName == "" {
		return nil, errors.New("keymanager/openbao: key_name is required")
	}

	transitPath := strings.Trim(strings.TrimSpace(opts.TransitPath), "/")
	if transitPath == "" {
		transitPath = defaultOpenBaoTransitPath
	}
	provider := opts.Provider
	if provider == "" {
		provider = defaultOpenBaoProvider
	}
	timeout := opts.Timeout
	if timeout <= 0 {
		timeout = defaultOpenBaoTimeout
	}

	cfg := bao.DefaultConfig()
	if cfg.Error != nil {
		return nil, fmt.Errorf("keymanager/openbao: default client config: %w", cfg.Error)
	}
	cfg.Address = opts.Address
	cfg.Timeout = timeout
	// Retries are owned by the RetryingKeyManager decorator, not the client.
	cfg.MaxRetries = 0
	if opts.TLSConfig != nil {
		if tr, ok := cfg.HttpClient.Transport.(*http.Transport); ok {
			tr.TLSClientConfig = opts.TLSConfig.Clone()
		}
	}

	client, err := bao.NewClient(cfg)
	if err != nil {
		return nil, fmt.Errorf("keymanager/openbao: create client: %w", err)
	}
	if opts.Namespace != "" {
		client.SetNamespace(opts.Namespace)
	}

	m := &openBaoTransitManager{
		client:      client,
		transitPath: transitPath,
		keyName:     opts.KeyName,
		keyID:       "vault-transit:" + transitPath + "/" + opts.KeyName,
		provider:    provider,
		timeout:     timeout,
		auth:        opts.Auth,
		freshSecret: make(chan leaseUpdate, 1),
		authSem:     make(chan struct{}, 1),
	}

	loginCtx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	// Through the same path every later login takes, so the generation and
	// lastAuthAt bookkeeping lives in exactly one place and the startup login is
	// counted by gateway_kms_reauth_total like the metric's help text says.
	// Uncontended here: nothing else holds a reference to m yet.
	m.authSem <- struct{}{}
	loginSecret, err := m.loginLocked(loginCtx)
	<-m.authSem
	if err != nil {
		return nil, fmt.Errorf("keymanager/openbao: initial login (method %q): %w", m.authMethod(), err)
	}

	if !opts.DisableRenewal && loginSecret != nil && loginSecret.Auth != nil &&
		loginSecret.Auth.Renewable && loginSecret.Auth.LeaseDuration > 0 {
		m.startRenewal(loginSecret)
	}

	return m, nil
}

func (m *openBaoTransitManager) authMethod() string {
	method := strings.ToLower(strings.TrimSpace(m.auth.Method))
	if method == "" {
		return openBaoAuthToken
	}
	return method
}

// Provider implements KeyManager.
func (m *openBaoTransitManager) Provider() string { return m.provider }

// WrapKey implements KeyManager: transit/encrypt of the gateway-supplied DEK.
func (m *openBaoTransitManager) WrapKey(ctx context.Context, plaintext []byte, _ map[string]string) (*KeyEnvelope, error) {
	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("keymanager/openbao: wrap: %w", err)
	}
	if len(plaintext) == 0 {
		return nil, errors.New("keymanager/openbao: plaintext DEK is empty")
	}
	// Contract: every method returns ErrProviderUnavailable after Close. The
	// client itself is re-resolved per attempt inside doRead/doWrite.
	if _, err := m.activeClient(); err != nil {
		return nil, err
	}

	rctx, cancel := m.withTimeout(ctx)
	defer cancel()

	secret, err := m.doWrite(rctx, m.path("encrypt"), map[string]any{
		"plaintext": base64.StdEncoding.EncodeToString(plaintext),
	})
	if err != nil {
		return nil, fmt.Errorf("keymanager/openbao: wrap (key %q): %w", m.keyName, m.classifyError(rctx, err))
	}
	if secret == nil || secret.Data == nil {
		return nil, fmt.Errorf("keymanager/openbao: wrap: empty response from transit/encrypt")
	}
	ct, ok := secret.Data["ciphertext"].(string)
	if !ok || ct == "" {
		return nil, fmt.Errorf("keymanager/openbao: wrap: missing ciphertext in response")
	}
	// Parse the version from the "vault:vN:" prefix rather than the response's
	// key_version field: the prefix is the single source of truth that travels
	// with the ciphertext and is what decrypt self-routes on, so deriving
	// KeyVersion from it keeps wrap/unwrap consistent.
	version, err := parseOpenBaoKeyVersion(ct)
	if err != nil {
		return nil, fmt.Errorf("keymanager/openbao: wrap: %w", err)
	}

	return &KeyEnvelope{
		KeyID:      m.keyID,
		KeyVersion: version,
		Provider:   m.provider,
		Ciphertext: []byte(ct),
		CreatedAt:  time.Now(),
	}, nil
}

// UnwrapKey implements KeyManager: transit/decrypt. No candidate loop — Transit
// self-routes to the version embedded in the ciphertext prefix.
func (m *openBaoTransitManager) UnwrapKey(ctx context.Context, envelope *KeyEnvelope, _ map[string]string) ([]byte, error) {
	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("keymanager/openbao: unwrap: %w", err)
	}
	// Closed check first: the interface requires every method to return
	// ErrProviderUnavailable after Close, regardless of arguments.
	// Contract: every method returns ErrProviderUnavailable after Close. The
	// client itself is re-resolved per attempt inside doRead/doWrite.
	if _, err := m.activeClient(); err != nil {
		return nil, err
	}
	if envelope == nil {
		return nil, fmt.Errorf("%w: envelope is nil", ErrInvalidEnvelope)
	}
	if len(envelope.Ciphertext) == 0 {
		return nil, fmt.Errorf("%w: wrapped key is empty", ErrInvalidEnvelope)
	}
	ciphertext := string(envelope.Ciphertext)
	if !strings.HasPrefix(ciphertext, openBaoCiphertextPrefix) {
		return nil, fmt.Errorf("%w: not an OpenBao Transit ciphertext", ErrInvalidEnvelope)
	}

	rctx, cancel := m.withTimeout(ctx)
	defer cancel()

	secret, err := m.doWrite(rctx, m.path("decrypt"), map[string]any{
		"ciphertext": ciphertext,
	})
	if err != nil {
		return nil, fmt.Errorf("keymanager/openbao: unwrap: %w", m.classifyError(rctx, err))
	}
	if secret == nil || secret.Data == nil {
		return nil, fmt.Errorf("%w: empty response from transit/decrypt", ErrUnwrapFailed)
	}
	b64, ok := secret.Data["plaintext"].(string)
	if !ok || b64 == "" {
		return nil, fmt.Errorf("%w: missing plaintext in decrypt response", ErrUnwrapFailed)
	}
	plain, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return nil, fmt.Errorf("%w: decode plaintext: %v", ErrUnwrapFailed, err)
	}
	return plain, nil
}

// ActiveKeyVersion implements KeyManager: live read of transit latest_version.
func (m *openBaoTransitManager) ActiveKeyVersion(ctx context.Context) (int, error) {
	if _, err := m.activeClient(); err != nil {
		return 0, err
	}
	rctx, cancel := m.withTimeout(ctx)
	defer cancel()

	secret, err := m.doRead(rctx, m.keysPath())
	if err != nil {
		return 0, fmt.Errorf("keymanager/openbao: read key metadata: %w", m.classifyError(rctx, err))
	}
	if secret == nil || secret.Data == nil {
		return 0, fmt.Errorf("%w: transit key %q not found", ErrKeyNotFound, m.keyName)
	}
	v, ok := toInt(secret.Data["latest_version"])
	if !ok {
		return 0, fmt.Errorf("keymanager/openbao: latest_version missing or non-numeric")
	}
	return v, nil
}

// HealthCheck implements KeyManager. It performs two lightweight, non-crypto
// reads:
//
//  1. auth/token/lookup-self — proves the token is valid (sys/health returns
//     200 even with an expired token, so it cannot detect expiry; GAP-KMS3-3).
//  2. transit/keys/<name>   — proves the configured key exists and is readable.
//     A wrong key_name, a deleted key, or a policy missing keys-read would
//     otherwise pass the token check while every wrap/unwrap 403/404s — a
//     "healthy but broken" data plane.
//
// On failure it returns ErrKeyNotFound (missing key) or ErrProviderUnavailable
// (everything else) so the health gauge reflects the true data-plane state.
func (m *openBaoTransitManager) HealthCheck(ctx context.Context) error {
	if _, err := m.activeClient(); err != nil {
		return err
	}
	rctx, cancel := m.withTimeout(ctx)
	defer cancel()

	// 1. Token validity + reachability.
	if _, err := m.doRead(rctx, "auth/token/lookup-self"); err != nil {
		ce := m.classifyError(rctx, err)
		if !errors.Is(ce, ErrProviderUnavailable) {
			ce = fmt.Errorf("%w: %v", ErrProviderUnavailable, ce)
		}
		return fmt.Errorf("keymanager/openbao: token lookup failed (expired/revoked token or server unreachable): %w", ce)
	}

	// 2. The configured Transit key exists and is readable.
	secret, err := m.doRead(rctx, m.keysPath())
	if err != nil {
		ce := m.classifyError(rctx, err)
		if errors.Is(ce, ErrKeyNotFound) {
			return fmt.Errorf("keymanager/openbao: transit key %q not found: %w", m.keyName, ce)
		}
		if !errors.Is(ce, ErrProviderUnavailable) {
			ce = fmt.Errorf("%w: %v", ErrProviderUnavailable, ce)
		}
		return fmt.Errorf("keymanager/openbao: transit key %q unreadable: %w", m.keyName, ce)
	}
	if secret == nil || secret.Data == nil {
		return fmt.Errorf("%w: transit key %q not found", ErrKeyNotFound, m.keyName)
	}
	return nil
}

// Close implements KeyManager. Idempotent. Stops the renewal goroutine.
func (m *openBaoTransitManager) Close(_ context.Context) error {
	m.mu.Lock()
	if m.closed {
		m.mu.Unlock()
		return nil
	}
	m.closed = true
	stop := m.stopRenew
	renewing := m.renewing
	done := m.renewDone
	// Cleared here, not just read: publishFreshLease gates on it to avoid
	// sending into a buffer no goroutine will ever drain.
	m.renewing = false
	m.mu.Unlock()

	if renewing && stop != nil {
		close(stop)
		if done != nil {
			<-done // wait for clean exit so -race sees no dangling goroutine
		}
	}
	return nil
}

// ---- RotatableKeyManager ---------------------------------------------------

// PrepareRotation implements RotatableKeyManager. Transit auto-increments on
// rotate, so the target is deterministically current+1.
func (m *openBaoTransitManager) PrepareRotation(ctx context.Context, target *int) (RotationPlan, error) {
	current, err := m.ActiveKeyVersion(ctx)
	if err != nil {
		return RotationPlan{}, err
	}
	if target != nil && *target != current+1 {
		return RotationPlan{}, fmt.Errorf("%w: OpenBao Transit can only mint the next version (current %d, target must be %d, got %d)",
			ErrRotationAmbiguous, current, current+1, *target)
	}
	return RotationPlan{
		CurrentVersion: current,
		TargetVersion:  current + 1,
		ProviderData:   map[string]string{"key_name": m.keyName, "transit_path": m.transitPath},
	}, nil
}

// PromoteActiveVersion implements RotatableKeyManager. It issues the server-side
// rotate RPC (minting current+1) and confirms latest_version advanced. The
// gateway FOLLOWS the server's version; it does not own an in-memory active
// version like the Cosmian adapter.
func (m *openBaoTransitManager) PromoteActiveVersion(ctx context.Context, plan RotationPlan) error {
	if _, err := m.activeClient(); err != nil {
		return err
	}

	current, err := m.ActiveKeyVersion(ctx)
	if err != nil {
		return err
	}
	if current != plan.CurrentVersion {
		return fmt.Errorf("%w: expected current version %d but live latest_version is %d", ErrRotationConflict, plan.CurrentVersion, current)
	}

	rctx, cancel := m.withTimeout(ctx)
	defer cancel()
	// Safe to re-authenticate and retry: a 403 means the rotate was rejected
	// before it ran, so no version was minted.
	if _, err := m.doWrite(rctx, m.keysPath()+"/rotate", nil); err != nil {
		return fmt.Errorf("keymanager/openbao: rotate key %q: %w", m.keyName, m.classifyError(rctx, err))
	}

	newVer, err := m.ActiveKeyVersion(ctx)
	if err != nil {
		return err
	}
	if newVer != plan.TargetVersion {
		return fmt.Errorf("%w: rotate produced version %d, expected %d", ErrRotationConflict, newVer, plan.TargetVersion)
	}
	return nil
}

// ---- helpers ---------------------------------------------------------------

// path builds a transit operation path: "<transitPath>/<op>/<keyName>".
func (m *openBaoTransitManager) path(op string) string {
	return m.transitPath + "/" + op + "/" + m.keyName
}

func (m *openBaoTransitManager) keysPath() string {
	return m.transitPath + "/keys/" + m.keyName
}

// activeClient returns the client if the manager is open, else
// ErrProviderUnavailable.
func (m *openBaoTransitManager) activeClient() (*bao.Client, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if m.closed {
		return nil, ErrProviderUnavailable
	}
	return m.client, nil
}

func (m *openBaoTransitManager) withTimeout(ctx context.Context) (context.Context, context.CancelFunc) {
	if ctx == nil {
		ctx = context.Background()
	}
	if m.timeout <= 0 {
		return ctx, func() {}
	}
	return context.WithTimeout(ctx, m.timeout)
}

// classifyError maps OpenBao API errors to the package's sentinel errors so the
// decorator chain and callers can react. Note: the retry decorator treats ALL
// sentinels (including ErrProviderUnavailable) as permanent, so a 403 is never
// retried by the chain. Recovering from a rejected credential is this adapter's
// job — see withAuthRetry — not the decorator's.
func (m *openBaoTransitManager) classifyError(ctx context.Context, err error) error {
	if err == nil {
		return nil
	}
	if ctx != nil && ctx.Err() != nil {
		return ctx.Err()
	}
	if code, ok := baoStatus(err); ok {
		switch code {
		case http.StatusForbidden, http.StatusUnauthorized:
			return fmt.Errorf("%w: %v", ErrProviderUnavailable, err)
		case http.StatusNotFound:
			return fmt.Errorf("%w: %v", ErrKeyNotFound, err)
		case http.StatusBadRequest:
			return fmt.Errorf("%w: %v", ErrUnwrapFailed, err)
		}
	}
	return err
}

// parseOpenBaoKeyVersion extracts N from a "vault:vN:<base64>" ciphertext.
// It never silently returns 0: an unparseable prefix is an error.
func parseOpenBaoKeyVersion(ciphertext string) (int, error) {
	rest, ok := strings.CutPrefix(ciphertext, openBaoCiphertextPrefix)
	if !ok {
		return 0, fmt.Errorf("ciphertext %q does not start with %q", truncForErr(ciphertext), openBaoCiphertextPrefix)
	}
	digits, _, ok := strings.Cut(rest, ":")
	if !ok || digits == "" {
		return 0, fmt.Errorf("ciphertext %q has no version delimiter", truncForErr(ciphertext))
	}
	n, err := strconv.Atoi(digits)
	if err != nil || n <= 0 {
		return 0, fmt.Errorf("ciphertext %q has invalid version %q", truncForErr(ciphertext), digits)
	}
	return n, nil
}

// truncForErr trims a ciphertext for safe inclusion in an error message
// (avoids dumping the full wrapped key into logs).
func truncForErr(s string) string {
	const max = 16
	if len(s) > max {
		return s[:max] + "…"
	}
	return s
}

// toInt coerces a JSON-decoded numeric value (json.Number, float64, int, or a
// numeric string) into an int.
func toInt(v any) (int, bool) {
	switch n := v.(type) {
	case json.Number:
		i, err := n.Int64()
		return int(i), err == nil
	case float64:
		return int(n), true
	case int:
		return n, true
	case int64:
		return int(n), true
	case string:
		i, err := strconv.Atoi(n)
		return i, err == nil
	default:
		return 0, false
	}
}

// ---- auth & token renewal --------------------------------------------------

// baoStatus extracts the HTTP status from an OpenBao API error. The status ->
// meaning table lives here only; classifyError and isOpenBaoAuthError both read
// it rather than each unwrapping *bao.ResponseError themselves.
func baoStatus(err error) (int, bool) {
	var respErr *bao.ResponseError
	if !errors.As(err, &respErr) {
		return 0, false
	}
	return respErr.StatusCode, true
}

// isOpenBaoAuthError reports whether err is OpenBao rejecting the credential
// itself (401/403) rather than any other failure. This is the only class of
// error a re-login can fix; 5xx, timeouts and connection errors are the
// server's problem and must not trigger one.
func isOpenBaoAuthError(err error) bool {
	code, ok := baoStatus(err)
	return ok && (code == http.StatusForbidden || code == http.StatusUnauthorized)
}

// authGeneration returns the current auth generation. Deliberately lock-free:
// this is read on every request, and authSem is held across login round-trips.
func (m *openBaoTransitManager) authGeneration() uint64 {
	return m.authGen.Load()
}

// acquireAuth takes the login semaphore, giving up when ctx expires, and reports
// whether it was acquired. Release with releaseAuth.
//
// Cancellable acquisition is the point: a login round-trip happens while the
// semaphore is held, and a request that cannot afford to wait that long must be
// able to walk away rather than overrun its own deadline. Whoever holds it is
// very likely performing the login that fixes the caller's problem anyway.
func (m *openBaoTransitManager) acquireAuth(ctx context.Context) bool {
	select {
	case m.authSem <- struct{}{}:
		return true
	case <-ctx.Done():
		return false
	}
}

func (m *openBaoTransitManager) releaseAuth() { <-m.authSem }

// loginLocked logs in and bumps the auth generation. Callers must hold authSem.
// It returns the login secret so the caller can hand a fresh lease to the
// renewal goroutine; it does not publish one itself.
func (m *openBaoTransitManager) loginLocked(ctx context.Context) (*bao.Secret, error) {
	// The floor lives here rather than in one caller, so BOTH the renewal
	// goroutine and the on-demand path are covered by construction.
	if wait := minLoginInterval - time.Since(m.lastLoginAttempt); wait > 0 {
		if !sleepCtx(ctx, wait) {
			return nil, ctx.Err()
		}
	}
	m.lastLoginAttempt = time.Now()

	secret, err := m.login(ctx)
	if fn := getRecordKMSReauthFn(); fn != nil {
		outcome := "success"
		if err != nil {
			outcome = "failure"
		}
		fn(m.provider, m.authMethod(), outcome)
	}
	if err != nil {
		return nil, err
	}
	m.authGen.Add(1)
	return secret, nil
}

// publishFreshLease hands a lease to the renewal goroutine so it stops watching
// the dead one. Only meaningful while that goroutine is running; otherwise the
// send is skipped so a *bao.Secret is not pinned in the buffer for the lifetime
// of the manager.
func (m *openBaoTransitManager) publishFreshLease(gen uint64, secret *bao.Secret) {
	if secret == nil {
		return
	}
	m.mu.RLock()
	live := m.renewing && !m.closed
	m.mu.RUnlock()
	if !live {
		// No goroutine will ever drain it, so sending would pin the secret (and
		// the whole login response) for the lifetime of the manager.
		return
	}
	select {
	case m.freshSecret <- leaseUpdate{gen: gen, secret: secret}:
	default: // a lease is already queued; the receiver discards stale ones by gen
	}
}

// refreshAuth re-logs-in on demand, unless another caller already did so since
// gen was captured. Rate-limited by minOnDemandReauthInterval.
//
// The login inherits the calling request's deadline rather than taking a longer
// one of its own: this runs inline in a request, so it must not overrun the
// caller's timeout. The renewal goroutine's reauth path is the one that gets a
// generous budget, because nobody is waiting on it.
//
// The "token" auth method is exempt: the operator owns that token's lifecycle
// and there is nothing to re-fetch, so a refresh would burn the rate limit
// re-setting the same dead string.
func (m *openBaoTransitManager) refreshAuth(ctx context.Context, gen uint64) error {
	if m.authMethod() == openBaoAuthToken {
		return errors.New("keymanager/openbao: static token auth cannot be refreshed")
	}
	m.mu.RLock()
	closed := m.closed
	m.mu.RUnlock()
	if closed {
		return ErrProviderUnavailable
	}

	// Cheap checks BEFORE taking the semaphore: a caller that is not going to
	// log in must not queue behind one, or it burns its whole deadline waiting
	// for a lock only to discover it had nothing to do.
	if m.authGeneration() != gen {
		return nil // someone already re-logged-in; just retry
	}

	// Leave the retry some budget. Handing the login the caller's entire
	// deadline means a slow login "succeeds" into an already-expired context and
	// the retried operation fails anyway.
	lctx, cancel := context.WithTimeout(ctx, m.reauthBudget(ctx))
	defer cancel()

	if !m.acquireAuth(lctx) {
		// Gave up waiting. Whoever holds the semaphore is logging in right now,
		// so the caller's next attempt will most likely succeed anyway.
		return errors.New("keymanager/openbao: timed out waiting to re-login")
	}
	defer m.releaseAuth()

	// Re-check under the semaphore: the holder we waited for may have been
	// logging in on our behalf.
	if m.authGeneration() != gen {
		return nil
	}

	secret, err := m.loginLocked(lctx)
	if err != nil {
		return err
	}
	m.publishFreshLease(m.authGeneration(), secret)
	return nil
}

// reauthBudget gives an inline re-login at most half the caller's remaining
// deadline, so the retry it exists to enable still has time to run.
func (m *openBaoTransitManager) reauthBudget(ctx context.Context) time.Duration {
	const fallback = 2 * time.Second
	deadline, ok := ctx.Deadline()
	if !ok {
		return fallback
	}
	half := time.Until(deadline) / 2
	if half <= 0 {
		return time.Millisecond // already out of budget; fail fast
	}
	return half
}

// sleepCtx sleeps for d unless ctx finishes first, reporting whether it slept.
func sleepCtx(ctx context.Context, d time.Duration) bool {
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-ctx.Done():
		return false
	case <-t.C:
		return true
	}
}

// withAuthRetry runs op and, if it fails because the credential was rejected,
// re-logs-in once and runs it again.
//
// This is the reactive half of token lifecycle management; the renewal goroutine
// is the proactive half. See the token-lifecycle note in the file header for why
// both are needed.
//
// It does not depend on data-plane traffic to fire: CircuitBreakerKeyManager
// delegates HealthCheck straight through without consulting breaker state, so
// the 30s health-check loop reaches this even with the breaker open and the S3
// front end idle.
func (m *openBaoTransitManager) withAuthRetry(ctx context.Context, op func() (*bao.Secret, error)) (*bao.Secret, error) {
	gen := m.authGeneration()
	secret, err := op()
	if err == nil || !isOpenBaoAuthError(err) {
		return secret, err
	}
	if rerr := m.refreshAuth(ctx, gen); rerr != nil {
		// Re-login is impossible or throttled: surface the original auth error,
		// which is the more useful diagnosis.
		return secret, err
	}
	return op()
}

// doWrite issues a Logical().Write, re-authenticating once on a rejected
// credential.
func (m *openBaoTransitManager) doWrite(ctx context.Context, path string, data map[string]any) (*bao.Secret, error) {
	return m.withAuthRetry(ctx, func() (*bao.Secret, error) {
		// Re-resolved per attempt: the retry runs after a login round-trip, and
		// Close may have landed in between.
		client, err := m.activeClient()
		if err != nil {
			return nil, err
		}
		return client.Logical().WriteWithContext(ctx, path, data)
	})
}

// doRead issues a Logical().Read, re-authenticating once on a rejected
// credential.
func (m *openBaoTransitManager) doRead(ctx context.Context, path string) (*bao.Secret, error) {
	return m.withAuthRetry(ctx, func() (*bao.Secret, error) {
		client, err := m.activeClient()
		if err != nil {
			return nil, err
		}
		return client.Logical().ReadWithContext(ctx, path)
	})
}

// login performs the configured authentication method and sets the resulting
// token on the client. For the "token" method it sets the static token and
// returns a nil secret (nothing to renew). For approle/kubernetes it returns
// the login *Secret so the caller can drive renewal.
func (m *openBaoTransitManager) login(ctx context.Context) (*bao.Secret, error) {
	switch m.authMethod() {
	case openBaoAuthToken:
		token := strings.TrimSpace(m.auth.Token)
		if token == "" {
			return nil, errors.New("token auth requires a token")
		}
		m.client.SetToken(token)
		return nil, nil

	case openBaoAuthAppRole:
		if m.auth.RoleID == "" {
			return nil, errors.New("approle auth requires role_id")
		}
		if m.auth.SecretID == "" {
			return nil, errors.New("approle auth requires secret_id")
		}
		mount := m.auth.Mount
		if mount == "" {
			mount = openBaoAuthAppRole
		}
		return m.doLogin(ctx, "auth/"+mount+"/login", map[string]any{
			"role_id":   m.auth.RoleID,
			"secret_id": m.auth.SecretID,
		})

	case openBaoAuthKubernetes:
		if m.auth.Role == "" {
			return nil, errors.New("kubernetes auth requires role")
		}
		jwt := m.auth.JWT
		if jwt == "" {
			path := m.auth.JWTPath
			if path == "" {
				path = defaultOpenBaoSAJWTPath
			}
			data, err := os.ReadFile(path) //nolint:gosec // operator-configured well-known path
			if err != nil {
				return nil, fmt.Errorf("read service account token %q: %w", path, err)
			}
			jwt = strings.TrimSpace(string(data))
		}
		if jwt == "" {
			return nil, errors.New("kubernetes auth: service account token is empty")
		}
		mount := m.auth.Mount
		if mount == "" {
			mount = openBaoAuthKubernetes
		}
		return m.doLogin(ctx, "auth/"+mount+"/login", map[string]any{
			"role": m.auth.Role,
			"jwt":  jwt,
		})

	default:
		return nil, fmt.Errorf("unsupported auth method %q (supported: token, approle, kubernetes)", m.authMethod())
	}
}

// doLogin posts credentials to a login path and sets the returned client token.
func (m *openBaoTransitManager) doLogin(ctx context.Context, path string, data map[string]any) (*bao.Secret, error) {
	secret, err := m.client.Logical().WriteWithContext(ctx, path, data)
	if err != nil {
		return nil, m.classifyError(ctx, err)
	}
	if secret == nil || secret.Auth == nil || secret.Auth.ClientToken == "" {
		return nil, errors.New("login response did not contain a client token")
	}
	m.client.SetToken(secret.Auth.ClientToken)
	return secret, nil
}

// startRenewal launches the background renewal goroutine.
func (m *openBaoTransitManager) startRenewal(initial *bao.Secret) {
	m.mu.Lock()
	m.renewing = true
	m.stopRenew = make(chan struct{})
	m.renewDone = make(chan struct{})
	stop := m.stopRenew
	done := m.renewDone
	m.mu.Unlock()
	go m.renewalLoop(initial, stop, done)
}

// renewalLoop keeps the auth token alive. It uses the OpenBao LifetimeWatcher
// (correct renewal timing: ~2/3 of remaining lease, jitter, backoff) and, when
// the watcher can no longer extend the token (DoneCh — fires at max_ttl, on
// revocation, or on server restart), RE-LOGS-IN. DoneCh firing is normal, not
// an error: re-login is the mandatory outer safeguard.
func (m *openBaoTransitManager) renewalLoop(secret *bao.Secret, stop <-chan struct{}, done chan<- struct{}) {
	defer close(done)
	backoff := time.Second
	const maxBackoff = 5 * time.Minute

	for {
		// If we have no renewable secret, re-login before watching. Note that
		// `backoff` is deliberately NOT reset here on a successful login: a login
		// that succeeds and is immediately followed by a watcher that cannot renew
		// is the storm case below, and resetting would defeat its escalation.
		if secret == nil || secret.Auth == nil || !secret.Auth.Renewable || secret.Auth.LeaseDuration == 0 {
			ns, err := m.reauth(stop)
			if err != nil {
				if !sleepOrStop(stop, backoff) {
					return
				}
				backoff = nextBackoff(backoff, maxBackoff)
				continue
			}
			secret = ns
		}

		// RenewBehavior matters here. The zero value is RenewBehaviorIgnoreErrors,
		// under which a failing renew-self does NOT close DoneCh: the watcher
		// keeps looping until the ORIGINAL lease elapses, so a token revoked or
		// expired early goes unnoticed for up to a full lease period (1h in a
		// typical deployment) while every request 403s. ErrorOnErrors surfaces the
		// failure immediately so this loop can re-login.
		//
		// The cost of that promptness is the storm handled below: the watcher
		// issues its first renew-self IMMEDIATELY on Start (no initial sleep), so
		// a lease that can never be renewed comes straight back through DoneCh.
		watcher, err := m.client.NewLifetimeWatcher(&bao.LifetimeWatcherInput{
			Secret:        secret,
			RenewBehavior: bao.RenewBehaviorErrorOnErrors,
		})
		if err != nil {
			secret = nil
			if !sleepOrStop(stop, backoff) {
				return
			}
			backoff = nextBackoff(backoff, maxBackoff)
			continue
		}
		go watcher.Start()

		// renewed distinguishes "this token was fine for a while and has now aged
		// out" from "this token could never be renewed at all". Only the former
		// deserves an immediate re-login.
		renewed := false
		restartWatch := false
		for !restartWatch {
			select {
			case <-stop:
				watcher.Stop()
				return

			case <-watcher.DoneCh():
				watcher.Stop()
				secret = nil
				restartWatch = true
				if renewed {
					// Normal end of life: renewals worked, then stopped. Re-login
					// promptly, and reset the escalation.
					backoff = time.Second
					break
				}
				// The watcher never managed a single renewal, so re-logging in
				// produces another token that also cannot be renewed — an
				// unbounded token-minting loop against the KMS, since every
				// iteration is a real login. This is reachable from a role granted
				// lookup-self but not renew-self. Back off instead.
				if !sleepOrStop(stop, backoff) {
					return
				}
				backoff = nextBackoff(backoff, maxBackoff)

			case u := <-m.freshSecret:
				// The data path re-authenticated. Adopt its lease only if it is
				// still the current one: this goroutine may have logged in itself
				// while the update sat in the buffer, in which case adopting the
				// queued lease would leave the token actually in use unrenewed.
				if u.gen != m.authGeneration() {
					continue // stale; keep watching what we have
				}
				watcher.Stop()
				secret = u.secret
				backoff = time.Second
				restartWatch = true

			case <-watcher.RenewCh():
				renewed = true
				backoff = time.Second
			}
		}
	}
}

// reauth re-runs the configured login and is safe to call while WrapKey/
// UnwrapKey are in flight (SetToken on the client is internally synchronised).
func (m *openBaoTransitManager) reauth(stop <-chan struct{}) (*bao.Secret, error) {
	select {
	case <-stop:
		return nil, errors.New("renewal stopped")
	default:
	}
	// Re-login involves a network round-trip plus token issuance; give it a
	// more generous deadline than the per-request timeout so a momentarily slow
	// server does not abort renewal (the loop's backoff retries regardless).
	loginTimeout := m.timeout
	if loginTimeout < 15*time.Second {
		loginTimeout = 15 * time.Second
	}
	ctx, cancel := context.WithTimeout(context.Background(), loginTimeout)
	defer cancel()
	// Abort an in-flight re-login promptly if Close() signals stop, so a
	// graceful shutdown during an unreachable-server login is not blocked for
	// the full login timeout.
	go func() {
		select {
		case <-stop:
			cancel()
		case <-ctx.Done():
		}
	}()
	// Share authSem with the on-demand path so the two can never log in
	// concurrently, and so a data-path caller that captured the old generation
	// sees this login and simply retries instead of minting a second token.
	if !m.acquireAuth(ctx) {
		return nil, ctx.Err()
	}
	defer m.releaseAuth()
	// No publishFreshLease: this IS the renewal goroutine, and loginLocked
	// returns the secret straight back to it.
	return m.loginLocked(ctx)
}

func sleepOrStop(stop <-chan struct{}, d time.Duration) bool {
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-stop:
		return false
	case <-t.C:
		return true
	}
}

func nextBackoff(cur, max time.Duration) time.Duration {
	next := cur * 2
	if next > max {
		return max
	}
	return next
}
