package crypto

import (
	"context"
	"crypto/tls"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	bao "github.com/openbao/openbao/api/v2"
)

// OpenBao / HashiCorp Vault Transit adapter.
//
// This adapter wraps per-object DEKs using the Transit secrets engine. The DEK
// is generated by the gateway's engine and handed to WrapKey; the adapter only
// asks Transit to encrypt it (transit/encrypt/<key>) and later decrypt it
// (transit/decrypt/<key>). The KEK never leaves OpenBao and is non-exportable.
//
// Why Transit encrypt/decrypt rather than transit/datakey: the gateway already
// generates its own random DEK (see engine.go), so it only needs a wrap/unwrap
// service. transit/datakey would make OpenBao the DEK generator and break the
// input-plaintext -> output-envelope contract shared by every other adapter.
//
// Differences vs. the Cosmian KMIP adapter that a reader should know:
//   - There is NO client-side candidate loop / dual_read_window. The Transit
//     ciphertext is self-describing ("vault:vN:<base64>") and the server
//     auto-routes a decrypt to the embedded version N. UnwrapKey is a single
//     call; old envelopes keep decrypting until an operator raises
//     min_decryption_version server-side (a retire floor, not a client window).
//   - KeyID is synthesised ("vault-transit:<mount>/<key>") rather than returned
//     by the server. engine.go rejects a streaming decrypt when the persisted
//     KMS key ID is empty, so WrapKey MUST set a stable non-empty KeyID.
//   - The active version is owned by the server (latest_version) and read live,
//     not held in an in-memory slice.
//   - Transit issues no dynamic leases; the only lifecycle object is the auth
//     token, which the adapter renews in a background goroutine (see renew.go
//     section below) and re-logs-in when renewal can no longer extend it.

const (
	defaultOpenBaoProvider    = "openbao-transit"
	defaultOpenBaoTransitPath = "transit"
	defaultOpenBaoTimeout     = 5 * time.Second
	defaultOpenBaoSAJWTPath   = "/var/run/secrets/kubernetes.io/serviceaccount/token" //nolint:gosec // well-known path, not a credential

	// openBaoCiphertextPrefix is the fixed prefix of every Transit ciphertext.
	// The "vault:" literal is retained by OpenBao for wire compatibility.
	openBaoCiphertextPrefix = "vault:v"

	// Supported auth methods.
	openBaoAuthToken      = "token"
	openBaoAuthAppRole    = "approle"
	openBaoAuthKubernetes = "kubernetes"
)

// OpenBaoAuthConfig selects the OpenBao authentication method and its parameters.
//
// Secret material (Token, SecretID, JWT) is expected to be already resolved by
// the caller (the config layer resolves env:/file: references). It is never
// logged or placed into a KeyEnvelope.
type OpenBaoAuthConfig struct {
	// Method is one of "token", "approle", "kubernetes". Default: "token".
	Method string
	// Mount is the auth backend mount path. Defaults per method
	// (approle -> "approle", kubernetes -> "kubernetes").
	Mount string

	// Token is the OpenBao token for the "token" method.
	Token string

	// RoleID / SecretID are the AppRole credentials.
	RoleID   string
	SecretID string

	// Role is the role name for the kubernetes method.
	Role string
	// JWTPath is the file holding the projected ServiceAccount JWT.
	// Default: defaultOpenBaoSAJWTPath.
	JWTPath string
	// JWT, when non-empty, is used verbatim instead of reading JWTPath
	// (primarily for tests).
	JWT string
}

// OpenBaoTransitOptions configures the OpenBao Transit KeyManager.
type OpenBaoTransitOptions struct {
	// Address is the OpenBao server address, e.g. "https://bao.internal:8200".
	Address string
	// TransitPath is the mount path of the Transit engine. Default: "transit".
	TransitPath string
	// KeyName is the Transit key used for DEK wrap/unwrap. Required.
	KeyName string
	// Namespace is an optional namespace prefix (OpenBao/Vault Enterprise).
	Namespace string
	// Provider overrides the Provider() string. Default: "openbao-transit".
	Provider string
	// Timeout is the per-request timeout. Default: 5s.
	Timeout time.Duration
	// TLSConfig, when set, replaces the client transport's TLS configuration.
	TLSConfig *tls.Config
	// Auth holds the authentication configuration.
	Auth OpenBaoAuthConfig

	// DisableRenewal disables the background token-renewal goroutine. Intended
	// for tests and for the "token" auth method where the operator owns the
	// token lifecycle.
	DisableRenewal bool
}

type openBaoTransitManager struct {
	mu          sync.RWMutex
	client      *bao.Client
	transitPath string
	keyName     string
	keyID       string // synthesised, stable: "vault-transit:<mount>/<key>"
	provider    string
	timeout     time.Duration
	auth        OpenBaoAuthConfig
	closed      bool

	// renewal goroutine lifecycle. stopRenew is closed by Close to signal exit;
	// renewDone is closed by the goroutine on exit.
	renewing  bool
	stopRenew chan struct{}
	renewDone chan struct{}
}

// Compile-time assertions.
var (
	_ KeyManager          = (*openBaoTransitManager)(nil)
	_ RotatableKeyManager = (*openBaoTransitManager)(nil)
)

// NewOpenBaoTransitManager constructs an authenticated OpenBao Transit
// KeyManager. It fails closed: if the initial login fails the manager is not
// returned, so the gateway never silently downgrades to password-derived DEKs.
func NewOpenBaoTransitManager(opts OpenBaoTransitOptions) (KeyManager, error) {
	opts.Address = strings.TrimSpace(opts.Address)
	if opts.Address == "" {
		return nil, errors.New("keymanager/openbao: address is required")
	}
	opts.KeyName = strings.TrimSpace(opts.KeyName)
	if opts.KeyName == "" {
		return nil, errors.New("keymanager/openbao: key_name is required")
	}

	transitPath := strings.Trim(strings.TrimSpace(opts.TransitPath), "/")
	if transitPath == "" {
		transitPath = defaultOpenBaoTransitPath
	}
	provider := opts.Provider
	if provider == "" {
		provider = defaultOpenBaoProvider
	}
	timeout := opts.Timeout
	if timeout <= 0 {
		timeout = defaultOpenBaoTimeout
	}

	cfg := bao.DefaultConfig()
	if cfg.Error != nil {
		return nil, fmt.Errorf("keymanager/openbao: default client config: %w", cfg.Error)
	}
	cfg.Address = opts.Address
	cfg.Timeout = timeout
	// Retries are owned by the RetryingKeyManager decorator, not the client.
	cfg.MaxRetries = 0
	if opts.TLSConfig != nil {
		if tr, ok := cfg.HttpClient.Transport.(*http.Transport); ok {
			tr.TLSClientConfig = opts.TLSConfig.Clone()
		}
	}

	client, err := bao.NewClient(cfg)
	if err != nil {
		return nil, fmt.Errorf("keymanager/openbao: create client: %w", err)
	}
	if opts.Namespace != "" {
		client.SetNamespace(opts.Namespace)
	}

	m := &openBaoTransitManager{
		client:      client,
		transitPath: transitPath,
		keyName:     opts.KeyName,
		keyID:       "vault-transit:" + transitPath + "/" + opts.KeyName,
		provider:    provider,
		timeout:     timeout,
		auth:        opts.Auth,
	}

	loginCtx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	loginSecret, err := m.login(loginCtx)
	if err != nil {
		return nil, fmt.Errorf("keymanager/openbao: initial login (method %q): %w", m.authMethod(), err)
	}

	if !opts.DisableRenewal && loginSecret != nil && loginSecret.Auth != nil &&
		loginSecret.Auth.Renewable && loginSecret.Auth.LeaseDuration > 0 {
		m.startRenewal(loginSecret)
	}

	return m, nil
}

func (m *openBaoTransitManager) authMethod() string {
	method := strings.ToLower(strings.TrimSpace(m.auth.Method))
	if method == "" {
		return openBaoAuthToken
	}
	return method
}

// Provider implements KeyManager.
func (m *openBaoTransitManager) Provider() string { return m.provider }

// WrapKey implements KeyManager: transit/encrypt of the gateway-supplied DEK.
func (m *openBaoTransitManager) WrapKey(ctx context.Context, plaintext []byte, _ map[string]string) (*KeyEnvelope, error) {
	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("keymanager/openbao: wrap: %w", err)
	}
	if len(plaintext) == 0 {
		return nil, errors.New("keymanager/openbao: plaintext DEK is empty")
	}
	client, err := m.activeClient()
	if err != nil {
		return nil, err
	}

	rctx, cancel := m.withTimeout(ctx)
	defer cancel()

	secret, err := client.Logical().WriteWithContext(rctx, m.path("encrypt"), map[string]any{
		"plaintext": base64.StdEncoding.EncodeToString(plaintext),
	})
	if err != nil {
		return nil, fmt.Errorf("keymanager/openbao: wrap (key %q): %w", m.keyName, m.classifyError(rctx, err))
	}
	if secret == nil || secret.Data == nil {
		return nil, fmt.Errorf("keymanager/openbao: wrap: empty response from transit/encrypt")
	}
	ct, ok := secret.Data["ciphertext"].(string)
	if !ok || ct == "" {
		return nil, fmt.Errorf("keymanager/openbao: wrap: missing ciphertext in response")
	}
	// Parse the version from the "vault:vN:" prefix rather than the response's
	// key_version field: the prefix is the single source of truth that travels
	// with the ciphertext and is what decrypt self-routes on, so deriving
	// KeyVersion from it keeps wrap/unwrap consistent.
	version, err := parseOpenBaoKeyVersion(ct)
	if err != nil {
		return nil, fmt.Errorf("keymanager/openbao: wrap: %w", err)
	}

	return &KeyEnvelope{
		KeyID:      m.keyID,
		KeyVersion: version,
		Provider:   m.provider,
		Ciphertext: []byte(ct),
		CreatedAt:  time.Now(),
	}, nil
}

// UnwrapKey implements KeyManager: transit/decrypt. No candidate loop — Transit
// self-routes to the version embedded in the ciphertext prefix.
func (m *openBaoTransitManager) UnwrapKey(ctx context.Context, envelope *KeyEnvelope, _ map[string]string) ([]byte, error) {
	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("keymanager/openbao: unwrap: %w", err)
	}
	// Closed check first: the interface requires every method to return
	// ErrProviderUnavailable after Close, regardless of arguments.
	client, err := m.activeClient()
	if err != nil {
		return nil, err
	}
	if envelope == nil {
		return nil, fmt.Errorf("%w: envelope is nil", ErrInvalidEnvelope)
	}
	if len(envelope.Ciphertext) == 0 {
		return nil, fmt.Errorf("%w: wrapped key is empty", ErrInvalidEnvelope)
	}
	ciphertext := string(envelope.Ciphertext)
	if !strings.HasPrefix(ciphertext, openBaoCiphertextPrefix) {
		return nil, fmt.Errorf("%w: not an OpenBao Transit ciphertext", ErrInvalidEnvelope)
	}

	rctx, cancel := m.withTimeout(ctx)
	defer cancel()

	secret, err := client.Logical().WriteWithContext(rctx, m.path("decrypt"), map[string]any{
		"ciphertext": ciphertext,
	})
	if err != nil {
		return nil, fmt.Errorf("keymanager/openbao: unwrap: %w", m.classifyError(rctx, err))
	}
	if secret == nil || secret.Data == nil {
		return nil, fmt.Errorf("%w: empty response from transit/decrypt", ErrUnwrapFailed)
	}
	b64, ok := secret.Data["plaintext"].(string)
	if !ok || b64 == "" {
		return nil, fmt.Errorf("%w: missing plaintext in decrypt response", ErrUnwrapFailed)
	}
	plain, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return nil, fmt.Errorf("%w: decode plaintext: %v", ErrUnwrapFailed, err)
	}
	return plain, nil
}

// ActiveKeyVersion implements KeyManager: live read of transit latest_version.
func (m *openBaoTransitManager) ActiveKeyVersion(ctx context.Context) (int, error) {
	client, err := m.activeClient()
	if err != nil {
		return 0, err
	}
	rctx, cancel := m.withTimeout(ctx)
	defer cancel()

	secret, err := client.Logical().ReadWithContext(rctx, m.keysPath())
	if err != nil {
		return 0, fmt.Errorf("keymanager/openbao: read key metadata: %w", m.classifyError(rctx, err))
	}
	if secret == nil || secret.Data == nil {
		return 0, fmt.Errorf("%w: transit key %q not found", ErrKeyNotFound, m.keyName)
	}
	v, ok := toInt(secret.Data["latest_version"])
	if !ok {
		return 0, fmt.Errorf("keymanager/openbao: latest_version missing or non-numeric")
	}
	return v, nil
}

// HealthCheck implements KeyManager. It performs two lightweight, non-crypto
// reads:
//
//  1. auth/token/lookup-self — proves the token is valid (sys/health returns
//     200 even with an expired token, so it cannot detect expiry; GAP-KMS3-3).
//  2. transit/keys/<name>   — proves the configured key exists and is readable.
//     A wrong key_name, a deleted key, or a policy missing keys-read would
//     otherwise pass the token check while every wrap/unwrap 403/404s — a
//     "healthy but broken" data plane.
//
// On failure it returns ErrKeyNotFound (missing key) or ErrProviderUnavailable
// (everything else) so the health gauge reflects the true data-plane state.
func (m *openBaoTransitManager) HealthCheck(ctx context.Context) error {
	client, err := m.activeClient()
	if err != nil {
		return err
	}
	rctx, cancel := m.withTimeout(ctx)
	defer cancel()

	// 1. Token validity + reachability.
	if _, err := client.Logical().ReadWithContext(rctx, "auth/token/lookup-self"); err != nil {
		ce := m.classifyError(rctx, err)
		if !errors.Is(ce, ErrProviderUnavailable) {
			ce = fmt.Errorf("%w: %v", ErrProviderUnavailable, ce)
		}
		return fmt.Errorf("keymanager/openbao: token lookup failed (expired/revoked token or server unreachable): %w", ce)
	}

	// 2. The configured Transit key exists and is readable.
	secret, err := client.Logical().ReadWithContext(rctx, m.keysPath())
	if err != nil {
		ce := m.classifyError(rctx, err)
		if errors.Is(ce, ErrKeyNotFound) {
			return fmt.Errorf("keymanager/openbao: transit key %q not found: %w", m.keyName, ce)
		}
		if !errors.Is(ce, ErrProviderUnavailable) {
			ce = fmt.Errorf("%w: %v", ErrProviderUnavailable, ce)
		}
		return fmt.Errorf("keymanager/openbao: transit key %q unreadable: %w", m.keyName, ce)
	}
	if secret == nil || secret.Data == nil {
		return fmt.Errorf("%w: transit key %q not found", ErrKeyNotFound, m.keyName)
	}
	return nil
}

// Close implements KeyManager. Idempotent. Stops the renewal goroutine.
func (m *openBaoTransitManager) Close(_ context.Context) error {
	m.mu.Lock()
	if m.closed {
		m.mu.Unlock()
		return nil
	}
	m.closed = true
	stop := m.stopRenew
	renewing := m.renewing
	done := m.renewDone
	m.mu.Unlock()

	if renewing && stop != nil {
		close(stop)
		if done != nil {
			<-done // wait for clean exit so -race sees no dangling goroutine
		}
	}
	return nil
}

// ---- RotatableKeyManager ---------------------------------------------------

// PrepareRotation implements RotatableKeyManager. Transit auto-increments on
// rotate, so the target is deterministically current+1.
func (m *openBaoTransitManager) PrepareRotation(ctx context.Context, target *int) (RotationPlan, error) {
	current, err := m.ActiveKeyVersion(ctx)
	if err != nil {
		return RotationPlan{}, err
	}
	if target != nil && *target != current+1 {
		return RotationPlan{}, fmt.Errorf("%w: OpenBao Transit can only mint the next version (current %d, target must be %d, got %d)",
			ErrRotationAmbiguous, current, current+1, *target)
	}
	return RotationPlan{
		CurrentVersion: current,
		TargetVersion:  current + 1,
		ProviderData:   map[string]string{"key_name": m.keyName, "transit_path": m.transitPath},
	}, nil
}

// PromoteActiveVersion implements RotatableKeyManager. It issues the server-side
// rotate RPC (minting current+1) and confirms latest_version advanced. The
// gateway FOLLOWS the server's version; it does not own an in-memory active
// version like the Cosmian adapter.
func (m *openBaoTransitManager) PromoteActiveVersion(ctx context.Context, plan RotationPlan) error {
	client, err := m.activeClient()
	if err != nil {
		return err
	}

	current, err := m.ActiveKeyVersion(ctx)
	if err != nil {
		return err
	}
	if current != plan.CurrentVersion {
		return fmt.Errorf("%w: expected current version %d but live latest_version is %d", ErrRotationConflict, plan.CurrentVersion, current)
	}

	rctx, cancel := m.withTimeout(ctx)
	defer cancel()
	if _, err := client.Logical().WriteWithContext(rctx, m.keysPath()+"/rotate", nil); err != nil {
		return fmt.Errorf("keymanager/openbao: rotate key %q: %w", m.keyName, m.classifyError(rctx, err))
	}

	newVer, err := m.ActiveKeyVersion(ctx)
	if err != nil {
		return err
	}
	if newVer != plan.TargetVersion {
		return fmt.Errorf("%w: rotate produced version %d, expected %d", ErrRotationConflict, newVer, plan.TargetVersion)
	}
	return nil
}

// ---- helpers ---------------------------------------------------------------

// path builds a transit operation path: "<transitPath>/<op>/<keyName>".
func (m *openBaoTransitManager) path(op string) string {
	return m.transitPath + "/" + op + "/" + m.keyName
}

func (m *openBaoTransitManager) keysPath() string {
	return m.transitPath + "/keys/" + m.keyName
}

// activeClient returns the client if the manager is open, else
// ErrProviderUnavailable.
func (m *openBaoTransitManager) activeClient() (*bao.Client, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if m.closed {
		return nil, ErrProviderUnavailable
	}
	return m.client, nil
}

func (m *openBaoTransitManager) withTimeout(ctx context.Context) (context.Context, context.CancelFunc) {
	if ctx == nil {
		ctx = context.Background()
	}
	if m.timeout <= 0 {
		return ctx, func() {}
	}
	return context.WithTimeout(ctx, m.timeout)
}

// classifyError maps OpenBao API errors to the package's sentinel errors so the
// decorator chain and callers can react. Note: the retry decorator treats ALL
// sentinels (including ErrProviderUnavailable) as permanent, so a 403 from an
// expired token is NOT retried — the renewal goroutine is the line of defence.
func (m *openBaoTransitManager) classifyError(ctx context.Context, err error) error {
	if err == nil {
		return nil
	}
	if ctx != nil && ctx.Err() != nil {
		return ctx.Err()
	}
	var respErr *bao.ResponseError
	if errors.As(err, &respErr) {
		switch respErr.StatusCode {
		case http.StatusForbidden, http.StatusUnauthorized:
			return fmt.Errorf("%w: %v", ErrProviderUnavailable, err)
		case http.StatusNotFound:
			return fmt.Errorf("%w: %v", ErrKeyNotFound, err)
		case http.StatusBadRequest:
			return fmt.Errorf("%w: %v", ErrUnwrapFailed, err)
		}
	}
	return err
}

// parseOpenBaoKeyVersion extracts N from a "vault:vN:<base64>" ciphertext.
// It never silently returns 0: an unparseable prefix is an error.
func parseOpenBaoKeyVersion(ciphertext string) (int, error) {
	rest, ok := strings.CutPrefix(ciphertext, openBaoCiphertextPrefix)
	if !ok {
		return 0, fmt.Errorf("ciphertext %q does not start with %q", truncForErr(ciphertext), openBaoCiphertextPrefix)
	}
	digits, _, ok := strings.Cut(rest, ":")
	if !ok || digits == "" {
		return 0, fmt.Errorf("ciphertext %q has no version delimiter", truncForErr(ciphertext))
	}
	n, err := strconv.Atoi(digits)
	if err != nil || n <= 0 {
		return 0, fmt.Errorf("ciphertext %q has invalid version %q", truncForErr(ciphertext), digits)
	}
	return n, nil
}

// truncForErr trims a ciphertext for safe inclusion in an error message
// (avoids dumping the full wrapped key into logs).
func truncForErr(s string) string {
	const max = 16
	if len(s) > max {
		return s[:max] + "…"
	}
	return s
}

// toInt coerces a JSON-decoded numeric value (json.Number, float64, int, or a
// numeric string) into an int.
func toInt(v any) (int, bool) {
	switch n := v.(type) {
	case json.Number:
		i, err := n.Int64()
		return int(i), err == nil
	case float64:
		return int(n), true
	case int:
		return n, true
	case int64:
		return int(n), true
	case string:
		i, err := strconv.Atoi(n)
		return i, err == nil
	default:
		return 0, false
	}
}

// ---- auth & token renewal --------------------------------------------------

// login performs the configured authentication method and sets the resulting
// token on the client. For the "token" method it sets the static token and
// returns a nil secret (nothing to renew). For approle/kubernetes it returns
// the login *Secret so the caller can drive renewal.
func (m *openBaoTransitManager) login(ctx context.Context) (*bao.Secret, error) {
	switch m.authMethod() {
	case openBaoAuthToken:
		token := strings.TrimSpace(m.auth.Token)
		if token == "" {
			return nil, errors.New("token auth requires a token")
		}
		m.client.SetToken(token)
		return nil, nil

	case openBaoAuthAppRole:
		if m.auth.RoleID == "" {
			return nil, errors.New("approle auth requires role_id")
		}
		if m.auth.SecretID == "" {
			return nil, errors.New("approle auth requires secret_id")
		}
		mount := m.auth.Mount
		if mount == "" {
			mount = openBaoAuthAppRole
		}
		return m.doLogin(ctx, "auth/"+mount+"/login", map[string]any{
			"role_id":   m.auth.RoleID,
			"secret_id": m.auth.SecretID,
		})

	case openBaoAuthKubernetes:
		if m.auth.Role == "" {
			return nil, errors.New("kubernetes auth requires role")
		}
		jwt := m.auth.JWT
		if jwt == "" {
			path := m.auth.JWTPath
			if path == "" {
				path = defaultOpenBaoSAJWTPath
			}
			data, err := os.ReadFile(path) //nolint:gosec // operator-configured well-known path
			if err != nil {
				return nil, fmt.Errorf("read service account token %q: %w", path, err)
			}
			jwt = strings.TrimSpace(string(data))
		}
		if jwt == "" {
			return nil, errors.New("kubernetes auth: service account token is empty")
		}
		mount := m.auth.Mount
		if mount == "" {
			mount = openBaoAuthKubernetes
		}
		return m.doLogin(ctx, "auth/"+mount+"/login", map[string]any{
			"role": m.auth.Role,
			"jwt":  jwt,
		})

	default:
		return nil, fmt.Errorf("unsupported auth method %q (supported: token, approle, kubernetes)", m.authMethod())
	}
}

// doLogin posts credentials to a login path and sets the returned client token.
func (m *openBaoTransitManager) doLogin(ctx context.Context, path string, data map[string]any) (*bao.Secret, error) {
	secret, err := m.client.Logical().WriteWithContext(ctx, path, data)
	if err != nil {
		return nil, m.classifyError(ctx, err)
	}
	if secret == nil || secret.Auth == nil || secret.Auth.ClientToken == "" {
		return nil, errors.New("login response did not contain a client token")
	}
	m.client.SetToken(secret.Auth.ClientToken)
	return secret, nil
}

// startRenewal launches the background renewal goroutine.
func (m *openBaoTransitManager) startRenewal(initial *bao.Secret) {
	m.mu.Lock()
	m.renewing = true
	m.stopRenew = make(chan struct{})
	m.renewDone = make(chan struct{})
	stop := m.stopRenew
	done := m.renewDone
	m.mu.Unlock()
	go m.renewalLoop(initial, stop, done)
}

// renewalLoop keeps the auth token alive. It uses the OpenBao LifetimeWatcher
// (correct renewal timing: ~2/3 of remaining lease, jitter, backoff) and, when
// the watcher can no longer extend the token (DoneCh — fires at max_ttl, on
// revocation, or on server restart), RE-LOGS-IN. DoneCh firing is normal, not
// an error: re-login is the mandatory outer safeguard.
func (m *openBaoTransitManager) renewalLoop(secret *bao.Secret, stop <-chan struct{}, done chan<- struct{}) {
	defer close(done)
	backoff := time.Second
	const maxBackoff = 5 * time.Minute

	for {
		// If we have no renewable secret, re-login before watching.
		if secret == nil || secret.Auth == nil || !secret.Auth.Renewable || secret.Auth.LeaseDuration == 0 {
			ns, err := m.reauth(stop)
			if err != nil {
				if !sleepOrStop(stop, backoff) {
					return
				}
				backoff = nextBackoff(backoff, maxBackoff)
				continue
			}
			secret = ns
			backoff = time.Second
		}

		watcher, err := m.client.NewLifetimeWatcher(&bao.LifetimeWatcherInput{Secret: secret})
		if err != nil {
			secret = nil
			if !sleepOrStop(stop, backoff) {
				return
			}
			backoff = nextBackoff(backoff, maxBackoff)
			continue
		}
		go watcher.Start()

		relogin := false
		for !relogin {
			select {
			case <-stop:
				watcher.Stop()
				return
			case <-watcher.DoneCh():
				// Can no longer renew; drop down to re-login.
				watcher.Stop()
				secret = nil
				relogin = true
			case <-watcher.RenewCh():
				// Renewal succeeded; keep watching.
				backoff = time.Second
			}
		}
	}
}

// reauth re-runs the configured login and is safe to call while WrapKey/
// UnwrapKey are in flight (SetToken on the client is internally synchronised).
func (m *openBaoTransitManager) reauth(stop <-chan struct{}) (*bao.Secret, error) {
	select {
	case <-stop:
		return nil, errors.New("renewal stopped")
	default:
	}
	// Re-login involves a network round-trip plus token issuance; give it a
	// more generous deadline than the per-request timeout so a momentarily slow
	// server does not abort renewal (the loop's backoff retries regardless).
	loginTimeout := m.timeout
	if loginTimeout < 15*time.Second {
		loginTimeout = 15 * time.Second
	}
	ctx, cancel := context.WithTimeout(context.Background(), loginTimeout)
	defer cancel()
	// Abort an in-flight re-login promptly if Close() signals stop, so a
	// graceful shutdown during an unreachable-server login is not blocked for
	// the full login timeout.
	go func() {
		select {
		case <-stop:
			cancel()
		case <-ctx.Done():
		}
	}()
	return m.login(ctx)
}

func sleepOrStop(stop <-chan struct{}, d time.Duration) bool {
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-stop:
		return false
	case <-t.C:
		return true
	}
}

func nextBackoff(cur, max time.Duration) time.Duration {
	next := cur * 2
	if next > max {
		return max
	}
	return next
}
